name: Code Coverage

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version required for your project

      - name: Install dependencies
        run: yarn install  # Or use yarn if you prefer

      - name: Run tests with coverage and Upload coverage reports to Codecov
        run: yarn run coverage:codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}